name: Back tests CI

on:
  push:
    branches:
      - user-back
  pull_request:
    branches:
      - main
      - preparation

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        cd web-elniki-back
        npm install

    - name: Set environment variables
      env:
        MYSQL_HOST: localhost
        MYSQL_USER: root
        MYSQL_DATABASE: skiresortapp
      run: |
        echo "MYSQL_HOST=localhost" >> $GITHUB_ENV
        echo "MYSQL_USER=root" >> $GITHUB_ENV
        echo "MYSQL_DATABASE=skiresortapp" >> $GITHUB_ENV

    - name: Run tests
      run: |
        cd web-elniki-back
        npm test
