name: Back tests CI

on:
  push:
    branches:
      - user-back
  pull_request:
    branches:
      - main
      - preparation

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        cd web-elniki-back
        npm install

    - name: Run tests
      run: |
        cd web-elniki-back
        npm test
